### ISSUE TITLE
Investigate empty src attribute

### ISSUE THREAD

**Issue by banool** [banool/codenames-pictures#21] opened 2018-09-30 20:03 UTC
This data set (https://dport.me/writing/kelly1.txt) produces one tile with an empty image. I'm not sure what's up with that yet, investigate.

**Comment by jackwilsdon** [comment] 2018-10-02 10:15
This is caused by a trailing newline, fixed by excluding any lines consisting entirely of whitespace (see #24).

**Closed** 2018-10-02 19:30 UTC
